filter:
    excluded_paths:
        - 'tests/*'
        - 'vendors/*'
checks:
    php:
        code_rating: true
        duplication: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: false
build:
    environment:
            php: '5.6.9'
    tests:
        override:
            -
                command: 'vendor/bin/codecept build'
            -
                command: 'vendor/bin/codecept run --coverage-xml=report.xml'
                coverage:
                    file: 'tests/_output/report.xml'
                    format: 'php-clover'
    dependencies:
        before:
            - sudo composer self-update
